[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "cxid9114"
version = "1.0"
dependencies = [
    "h5py",
    "numpy",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["cxid9114*"]

[project.scripts]
"cxid9114.sim" = "cxid9114.sim.d9114_mpi_sims:main"
"cxid9114.install_format" = "cxid9114.format.install_format:main"

